# Generated by Django 4.1 on 2022-08-11 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_modified', models.DateField(auto_now=True, null=True)),
                ('aks_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aks_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
